mailto_reply:
  mailto_reply_enabled:
    default: false
    type: bool
    client: true
  mailto_reply_address:
    default: ""
    type: string
    client: true
  mailto_reply_include_quoted_text:
    default: true
    type: bool
    client: true
  mailto_reply_include_headers:
    default: true
    type: bool
    client: true
